#!/usr/bin/env python3
"""Regenerate the embedded Russian bootstrap fallback from localization/core/ru.json."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "localization" / "core" / "ru.json"
DESTINATION = ROOT / "scripts" / "localization" / "core_ru_fallback.gd"


def main() -> int:
    payload = json.loads(SOURCE.read_text(encoding="utf-8"))
    strings = payload.get("strings")
    if not isinstance(strings, dict) or not strings:
        raise SystemExit("ru.json does not contain a non-empty 'strings' object")
    normalized: dict[str, str] = {}
    for raw_key, raw_value in strings.items():
        if not isinstance(raw_key, str) or not isinstance(raw_value, str):
            raise SystemExit("ru.json localization keys and values must be strings")
        normalized[raw_key] = raw_value
    canonical = json.dumps(
        normalized,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")
    digest = hashlib.sha256(canonical).hexdigest()

    lines = [
        "# SPDX-License-Identifier: GPL-3.0-or-later",
        "# AUTO-GENERATED FROM res://localization/core/ru.json.",
        f"# SOURCE_SHA256: {digest}",
        "# Do not edit this file by hand; ru.json is the canonical source.",
        "class_name NotLightCoreRuFallback",
        "extends RefCounted",
        "",
        "",
        "static func strings() -> Dictionary:",
        "\treturn {",
    ]
    for key in sorted(normalized):
        key_literal = json.dumps(key, ensure_ascii=False)
        value_literal = json.dumps(normalized[key], ensure_ascii=False)
        lines.append(f"\t\t{key_literal}: {value_literal},")
    lines.extend(["\t}", ""])
    DESTINATION.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"Regenerated {DESTINATION.relative_to(ROOT)} ({len(normalized)} strings, SHA-256 {digest}).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
